### ISSUE TITLE
meta CI broken due to peer dependency problem in /themes

### ISSUE THREAD

**Issue by vinckr** [ory/themes#56]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/themes/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/themes/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The ory/meta sync workflow is failing due to some peer dependency errors in this repo
https://github.com/ory/meta/runs/6833819464?check_suite_focus=true

### Reproducing the bug

Could not reproduce this locally when running `npm ci`

### Relevant log output

```shell
+ npm ci
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @reach/router@1.3.4
npm WARN Found: react@17.0.2
npm WARN node_modules/react
npm WARN   dev react@"^17.0.2" from the root project
npm WARN   47 more (@emotion/core, @emotion/styled, @emotion/styled-base, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"15.x || 16.x || 16.4.0-alpha.0911da3" from @reach/router@1.3.4
npm WARN node_modules/@storybook/api/node_modules/@reach/router
npm WARN   @reach/router@"^1.3.4" from @storybook/api@6.3.7
npm WARN   node_modules/@storybook/api
npm WARN 
npm WARN Conflicting peer dependency: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"15.x || 16.x || 16.4.0-alpha.0911da3" from @reach/router@1.3.4
npm WARN   node_modules/@storybook/api/node_modules/@reach/router
npm WARN     @reach/router@"^1.3.4" from @storybook/api@6.3.7
npm WARN     node_modules/@storybook/api
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @reach/router@1.3.4
npm WARN Found: react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   dev react-dom@"^17.0.2" from the root project
npm WARN   31 more (@storybook/addon-actions, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"15.x || 16.x || 16.4.0-alpha.0911da3" from @reach/router@1.3.4
npm WARN node_modules/@storybook/api/node_modules/@reach/router
npm WARN   @reach/router@"^1.3.4" from @storybook/api@6.3.7
npm WARN   node_modules/@storybook/api
npm WARN 
npm WARN Conflicting peer dependency: react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"15.x || 16.x || 16.4.0-alpha.0911da3" from @reach/router@1.3.4
npm WARN   node_modules/@storybook/api/node_modules/@reach/router
npm WARN     @reach/router@"^1.3.4" from @storybook/api@6.3.7
npm WARN     node_modules/@storybook/api
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @reach/router@1.3.4
npm WARN Found: react@17.0.2
npm WARN node_modules/react
npm WARN   dev react@"^17.0.2" from the root project
npm WARN   47 more (@emotion/core, @emotion/styled, @emotion/styled-base, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"15.x || 16.x || 16.4.0-alpha.0911da3" from @reach/router@1.3.4
npm WARN node_modules/@storybook/router/node_modules/@reach/router
npm WARN   @reach/router@"^1.3.4" from @storybook/router@6.3.7
npm WARN   node_modules/@storybook/router
npm WARN 
npm WARN Conflicting peer dependency: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"15.x || 16.x || 16.4.0-alpha.0911da3" from @reach/router@1.3.4
npm WARN   node_modules/@storybook/router/node_modules/@reach/router
npm WARN     @reach/router@"^1.3.4" from @storybook/router@6.3.7
npm WARN     node_modules/@storybook/router
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @reach/router@1.3.4
npm WARN Found: react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   dev react-dom@"^17.0.2" from the root project
npm WARN   31 more (@storybook/addon-actions, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"15.x || 16.x || 16.4.0-alpha.0911da3" from @reach/router@1.3.4
npm WARN node_modules/@storybook/router/node_modules/@reach/router
npm WARN   @reach/router@"^1.3.4" from @storybook/router@6.3.7
npm WARN   node_modules/@storybook/router
npm WARN 
npm WARN Conflicting peer dependency: react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   peer react-dom@"15.x || 16.x || 16.4.0-alpha.0911da3" from @reach/router@1.3.4
npm WARN   node_modules/@storybook/router/node_modules/@reach/router
npm WARN     @reach/router@"^1.3.4" from @storybook/router@6.3.7
npm WARN     node_modules/@storybook/router
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: create-react-context@0.3.0
npm WARN Found: react@17.0.2
npm WARN node_modules/react
npm WARN   dev react@"^17.0.2" from the root project
npm WARN   47 more (@emotion/core, @emotion/styled, @emotion/styled-base, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^0.14.0 || ^15.0.0 || ^16.0.0" from create-react-context@0.3.0
npm WARN node_modules/@storybook/api/node_modules/@reach/router/node_modules/create-react-context
npm WARN   create-react-context@"0.3.0" from @reach/router@1.3.4
npm WARN   node_modules/@storybook/api/node_modules/@reach/router
npm WARN 
npm WARN Conflicting peer dependency: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"^0.14.0 || ^15.0.0 || ^16.0.0" from create-react-context@0.3.0
npm WARN   node_modules/@storybook/api/node_modules/@reach/router/node_modules/create-react-context
npm WARN     create-react-context@"0.3.0" from @reach/router@1.3.4
npm WARN     node_modules/@storybook/api/node_modules/@reach/router
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: create-react-context@0.3.0
npm WARN Found: react@17.0.2
npm WARN node_modules/react
npm WARN   dev react@"^17.0.2" from the root project
npm WARN   47 more (@emotion/core, @emotion/styled, @emotion/styled-base, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^0.14.0 || ^15.0.0 || ^16.0.0" from create-react-context@0.3.0
npm WARN node_modules/@storybook/router/node_modules/@reach/router/node_modules/create-react-context
npm WARN   create-react-context@"0.3.0" from @reach/router@1.3.4
npm WARN   node_modules/@storybook/router/node_modules/@reach/router
npm WARN 
npm WARN Conflicting peer dependency: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"^0.14.0 || ^15.0.0 || ^16.0.0" from create-react-context@0.3.0
npm WARN   node_modules/@storybook/router/node_modules/@reach/router/node_modules/create-react-context
npm WARN     create-react-context@"0.3.0" from @reach/router@1.3.4
npm WARN     node_modules/@storybook/router/node_modules/@reach/router
npm ERR! code EUSAGE
npm ERR! 
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! Invalid: lock file's type-fest@0.8.1 does not satisfy type-fest@0.13.1
npm ERR! Missing: type-fest@0.8.1 from lock file
npm ERR! Missing: type-fest@0.8.1 from lock file
npm ERR! 
npm ERR! Clean install a project
npm ERR! 
npm ERR! Usage:
npm ERR! npm ci
npm ERR! 
npm ERR! Options:
npm ERR! [--no-audit] [--foreground-scripts] [--ignore-scripts]
npm ERR! [--script-shell <script-shell>]
npm ERR! 
npm ERR! aliases: clean-install, ic, install-clean, isntall-clean
npm ERR! 
npm ERR! Run "npm help ci" for more info
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-06-10T15_43_45_820Z-debug-0.log
Error: Process completed with exit code 1.
```

### Version

none

### Additional Context

If you had some pointers on how to start resolving this, could not figure it out after some time. 
- I updated some peer dependencies manually
- deleted lockfile and cache and ran `npm i` again

not sure how to test that the fixes or reproduce the error locally, that is probably the biggest roadblock for me here.

**Comment by aeneasr** [comment]
fixed

https://github.com/ory/meta/runs/6924716670?check_suite_focus=true
